{
 "title": "Business & Utilisation MLOps",
 "tags": [
  "mlops",
  "business"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ml_predictions_total)" }
   ]
  },
  {
   "title": "Taux de Toxicité",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(ml_predictions_total{result=\"toxic\"}) / sum(ml_predictions_total) * 100"
    }
   ]
  },
  {
   "title": "Model Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ml_model_status" }
   ]
  },
  {
   "title": "Volume/Heure",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ml_predictions_total[1h]))"
    }
   ]
  },
  {
   "title": "Predictions par Classe",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ml_predictions_total{result=\"toxic\"}[5m])",
     "legendFormat": "Toxic"
    },
    {
     "expr": "rate(ml_predictions_total{result=\"non_toxic\"}[5m])",
     "legendFormat": "Non-Toxic"
    }
   ]
  }
 ]
}